// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBABodmBfEnKIAoq9eydHq3ayfxZiK85tQ',
    appId: '1:681070352481:web:b819e66e6438773bf97220',
    messagingSenderId: '681070352481',
    projectId: 'seproject-51872',
    authDomain: 'seproject-51872.firebaseapp.com',
    storageBucket: 'seproject-51872.appspot.com',
    measurementId: 'G-ZP8F4G9N41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDm1d-3na0955dFcs3FteQLdVF55W1d_U',
    appId: '1:681070352481:android:8c88b387bbb5fb0bf97220',
    messagingSenderId: '681070352481',
    projectId: 'seproject-51872',
    storageBucket: 'seproject-51872.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEME33ZHpxG-lDfckOuWRohrU7mtHwj0M',
    appId: '1:681070352481:ios:444b287a20ec12e6f97220',
    messagingSenderId: '681070352481',
    projectId: 'seproject-51872',
    storageBucket: 'seproject-51872.appspot.com',
    iosClientId: '681070352481-mrc0a6s95pm6d9moo4789t2dguk6de7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.selectableNavigationDrawerExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEME33ZHpxG-lDfckOuWRohrU7mtHwj0M',
    appId: '1:681070352481:ios:444b287a20ec12e6f97220',
    messagingSenderId: '681070352481',
    projectId: 'seproject-51872',
    storageBucket: 'seproject-51872.appspot.com',
    iosClientId: '681070352481-mrc0a6s95pm6d9moo4789t2dguk6de7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.selectableNavigationDrawerExample',
  );
}
